export const MITRA_CATEGORIES = [
  { id: 'all', label: 'Semua Kategori' },
  { id: 'business-economy', label: 'Ekonomi & Bisnis' },
  { id: 'education', label: 'Pendidikan' },
  { id: 'general-news', label: 'Berita Umum' },
  { id: 'health', label: 'Kesehatan' },
  { id: 'hobby', label: 'Hobi' },
  { id: 'leisure', label: 'Seni & Hiburan' },
  { id: 'religion', label: 'Agama' },
  { id: 'sport', label: 'Olahraga' },
] as const

export const MITRA_PROVINCES = [
  { id: 'all', label: 'Semua Provinsi' },
  { id: 'aceh', label: 'Aceh' },
  { id: 'bali', label: 'Bali' },
  { id: 'banten', label: 'Banten' },
  { id: 'bengkulu', label: 'Bengkulu' },
  { id: 'di-yogyakarta', label: 'DI Yogyakarta' },
  { id: 'dki-jakarta', label: 'DKI Jakarta' },
  { id: 'gorontalo', label: 'Gorontalo' },
  { id: 'jambi', label: 'Jambi' },
  { id: 'jawa-barat', label: 'Jawa Barat' },
  { id: 'jawa-tengah', label: 'Jawa Tengah' },
  { id: 'jawa-timur', label: 'Jawa Timur' },
  { id: 'kalimantan-barat', label: 'Kalimantan Barat' },
  { id: 'kalimantan-selatan', label: 'Kalimantan Selatan' },
  { id: 'kalimantan-tengah', label: 'Kalimantan Tengah' },
  { id: 'kalimantan-timur', label: 'Kalimantan Timur' },
  { id: 'kalimantan-utara', label: 'Kalimantan Utara' },
  { id: 'kepulauan-bangka-belitung', label: 'Kepulauan Bangka Belitung' },
  { id: 'kepulauan-riau', label: 'Kepulauan Riau' },
  { id: 'lampung', label: 'Lampung' },
  { id: 'maluku', label: 'Maluku' },
  { id: 'maluku-utara', label: 'Maluku Utara' },
  { id: 'nusa-tenggara-barat', label: 'Nusa Tenggara Barat' },
  { id: 'nusa-tenggara-timur', label: 'Nusa Tenggara Timur' },
  { id: 'papua', label: 'Papua' },
  { id: 'papua-tengah', label: 'Papua Tengah' },
  { id: 'riau', label: 'Riau' },
  { id: 'sulawesi-barat', label: 'Sulawesi Barat' },
  { id: 'sulawesi-selatan', label: 'Sulawesi Selatan' },
  { id: 'sulawesi-tengah', label: 'Sulawesi Tengah' },
  { id: 'sulawesi-tenggara', label: 'Sulawesi Tenggara' },
  { id: 'sulawesi-utara', label: 'Sulawesi Utara' },
  { id: 'sumatera-barat', label: 'Sumatera Barat' },
  { id: 'sumatera-selatan', label: 'Sumatera Selatan' },
  { id: 'sumatera-utara', label: 'Sumatera Utara' },
] as const

export type MitraCategoryId = (typeof MITRA_CATEGORIES)[number]['id']
export type MitraProvinceId = (typeof MITRA_PROVINCES)[number]['id']
